environment:
  name: test
  project: cdf-bootcamp-07-test
  validation-type: test
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      data_foundation:
        data_developer_source_id: abd1214c-484c-4e06-95bc-3f046d048664
      ice_cream_api:
        icapi_extractors_source_id: e4cd3351-878d-4f50-b1c8-13048a5b80ce
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

      use_cases:
        oee:
          data_pipeline_oee_source_id: 58e7c64d-35a4-46de-83b2-8b9d92162cc4
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
